/*
* @Author: gpinchon
* @Date:   2021-05-20 15:21:41
* @Last Modified by:   gpinchon
* @Last Modified time: 2021-07-01 22:12:49
*/

#include <Driver/SDL2/InputDevices/Keyboard.hpp>
#include <Events/Manager.hpp>
#include <Window.hpp>

#include <SDL_events.h>
#include <SDL_keyboard.h>

namespace TabGraph::SDL2::Keyboard {
    const static std::unordered_map<SDL_Scancode, TabGraph::Events::Keyboard::Key> s_keyLUT {
        { SDL_SCANCODE_UNKNOWN, TabGraph::Events::Keyboard::Key::Unknown },
        { SDL_SCANCODE_A, TabGraph::Events::Keyboard::Key::A },
        { SDL_SCANCODE_B, TabGraph::Events::Keyboard::Key::B },
        { SDL_SCANCODE_C, TabGraph::Events::Keyboard::Key::C },
        { SDL_SCANCODE_D, TabGraph::Events::Keyboard::Key::D },
        { SDL_SCANCODE_E, TabGraph::Events::Keyboard::Key::E },
        { SDL_SCANCODE_F, TabGraph::Events::Keyboard::Key::F },
        { SDL_SCANCODE_G, TabGraph::Events::Keyboard::Key::G },
        { SDL_SCANCODE_H, TabGraph::Events::Keyboard::Key::H },
        { SDL_SCANCODE_I, TabGraph::Events::Keyboard::Key::I },
        { SDL_SCANCODE_J, TabGraph::Events::Keyboard::Key::J },
        { SDL_SCANCODE_K, TabGraph::Events::Keyboard::Key::K },
        { SDL_SCANCODE_L, TabGraph::Events::Keyboard::Key::L },
        { SDL_SCANCODE_M, TabGraph::Events::Keyboard::Key::M },
        { SDL_SCANCODE_N, TabGraph::Events::Keyboard::Key::N },
        { SDL_SCANCODE_O, TabGraph::Events::Keyboard::Key::O },
        { SDL_SCANCODE_P, TabGraph::Events::Keyboard::Key::P },
        { SDL_SCANCODE_Q, TabGraph::Events::Keyboard::Key::Q },
        { SDL_SCANCODE_R, TabGraph::Events::Keyboard::Key::R },
        { SDL_SCANCODE_S, TabGraph::Events::Keyboard::Key::S },
        { SDL_SCANCODE_T, TabGraph::Events::Keyboard::Key::T },
        { SDL_SCANCODE_U, TabGraph::Events::Keyboard::Key::U },
        { SDL_SCANCODE_V, TabGraph::Events::Keyboard::Key::V },
        { SDL_SCANCODE_W, TabGraph::Events::Keyboard::Key::W },
        { SDL_SCANCODE_X, TabGraph::Events::Keyboard::Key::X },
        { SDL_SCANCODE_Y, TabGraph::Events::Keyboard::Key::Y },
        { SDL_SCANCODE_Z, TabGraph::Events::Keyboard::Key::Z },
        { SDL_SCANCODE_1, TabGraph::Events::Keyboard::Key::Num1 },
        { SDL_SCANCODE_2, TabGraph::Events::Keyboard::Key::Num2 },
        { SDL_SCANCODE_3, TabGraph::Events::Keyboard::Key::Num3 },
        { SDL_SCANCODE_4, TabGraph::Events::Keyboard::Key::Num4 },
        { SDL_SCANCODE_5, TabGraph::Events::Keyboard::Key::Num5 },
        { SDL_SCANCODE_6, TabGraph::Events::Keyboard::Key::Num6 },
        { SDL_SCANCODE_7, TabGraph::Events::Keyboard::Key::Num7 },
        { SDL_SCANCODE_8, TabGraph::Events::Keyboard::Key::Num8 },
        { SDL_SCANCODE_9, TabGraph::Events::Keyboard::Key::Num9 },
        { SDL_SCANCODE_0, TabGraph::Events::Keyboard::Key::Num0 },
        { SDL_SCANCODE_RETURN, TabGraph::Events::Keyboard::Key::Return },
        { SDL_SCANCODE_ESCAPE, TabGraph::Events::Keyboard::Key::Escape },
        { SDL_SCANCODE_BACKSPACE, TabGraph::Events::Keyboard::Key::Backspace },
        { SDL_SCANCODE_TAB, TabGraph::Events::Keyboard::Key::Tab },
        { SDL_SCANCODE_SPACE, TabGraph::Events::Keyboard::Key::Space },
        { SDL_SCANCODE_MINUS, TabGraph::Events::Keyboard::Key::Minus },
        { SDL_SCANCODE_EQUALS, TabGraph::Events::Keyboard::Key::Equals },
        { SDL_SCANCODE_LEFTBRACKET, TabGraph::Events::Keyboard::Key::LeftBracket },
        { SDL_SCANCODE_RIGHTBRACKET, TabGraph::Events::Keyboard::Key::RightBracket },
        { SDL_SCANCODE_BACKSLASH, TabGraph::Events::Keyboard::Key::Backslash },
        { SDL_SCANCODE_NONUSHASH, TabGraph::Events::Keyboard::Key::Nonushash },
        { SDL_SCANCODE_SEMICOLON, TabGraph::Events::Keyboard::Key::Semicolon },
        { SDL_SCANCODE_APOSTROPHE, TabGraph::Events::Keyboard::Key::Apostrophe },
        { SDL_SCANCODE_GRAVE, TabGraph::Events::Keyboard::Key::Grave },
        { SDL_SCANCODE_COMMA, TabGraph::Events::Keyboard::Key::Comma },
        { SDL_SCANCODE_PERIOD, TabGraph::Events::Keyboard::Key::Period },
        { SDL_SCANCODE_SLASH, TabGraph::Events::Keyboard::Key::Slash },
        { SDL_SCANCODE_CAPSLOCK, TabGraph::Events::Keyboard::Key::CapsLock },
        { SDL_SCANCODE_F1, TabGraph::Events::Keyboard::Key::F1 },
        { SDL_SCANCODE_F2, TabGraph::Events::Keyboard::Key::F2 },
        { SDL_SCANCODE_F3, TabGraph::Events::Keyboard::Key::F3 },
        { SDL_SCANCODE_F4, TabGraph::Events::Keyboard::Key::F4 },
        { SDL_SCANCODE_F5, TabGraph::Events::Keyboard::Key::F5 },
        { SDL_SCANCODE_F6, TabGraph::Events::Keyboard::Key::F6 },
        { SDL_SCANCODE_F7, TabGraph::Events::Keyboard::Key::F7 },
        { SDL_SCANCODE_F8, TabGraph::Events::Keyboard::Key::F8 },
        { SDL_SCANCODE_F9, TabGraph::Events::Keyboard::Key::F9 },
        { SDL_SCANCODE_F10, TabGraph::Events::Keyboard::Key::F10 },
        { SDL_SCANCODE_F11, TabGraph::Events::Keyboard::Key::F11 },
        { SDL_SCANCODE_F12, TabGraph::Events::Keyboard::Key::F12 },
        { SDL_SCANCODE_PRINTSCREEN, TabGraph::Events::Keyboard::Key::PrintScreen },
        { SDL_SCANCODE_SCROLLLOCK, TabGraph::Events::Keyboard::Key::ScrollLock },
        { SDL_SCANCODE_PAUSE, TabGraph::Events::Keyboard::Key::Pause },
        { SDL_SCANCODE_INSERT, TabGraph::Events::Keyboard::Key::Insert },
        { SDL_SCANCODE_HOME, TabGraph::Events::Keyboard::Key::Home },
        { SDL_SCANCODE_PAGEUP, TabGraph::Events::Keyboard::Key::PageUp },
        { SDL_SCANCODE_DELETE, TabGraph::Events::Keyboard::Key::Delete },
        { SDL_SCANCODE_END, TabGraph::Events::Keyboard::Key::End },
        { SDL_SCANCODE_PAGEDOWN, TabGraph::Events::Keyboard::Key::PageDown },
        { SDL_SCANCODE_RIGHT, TabGraph::Events::Keyboard::Key::Right },
        { SDL_SCANCODE_LEFT, TabGraph::Events::Keyboard::Key::Left },
        { SDL_SCANCODE_DOWN, TabGraph::Events::Keyboard::Key::Down },
        { SDL_SCANCODE_UP, TabGraph::Events::Keyboard::Key::Up },
        { SDL_SCANCODE_NUMLOCKCLEAR, TabGraph::Events::Keyboard::Key::NumLockclear },
        { SDL_SCANCODE_KP_DIVIDE, TabGraph::Events::Keyboard::Key::NumpadDivide },
        { SDL_SCANCODE_KP_MULTIPLY, TabGraph::Events::Keyboard::Key::NumpadMultiply },
        { SDL_SCANCODE_KP_MINUS, TabGraph::Events::Keyboard::Key::NumpadMinus },
        { SDL_SCANCODE_KP_PLUS, TabGraph::Events::Keyboard::Key::NumpadPlus },
        { SDL_SCANCODE_KP_ENTER, TabGraph::Events::Keyboard::Key::NumpadEnter },
        { SDL_SCANCODE_KP_1, TabGraph::Events::Keyboard::Key::Numpad1 },
        { SDL_SCANCODE_KP_2, TabGraph::Events::Keyboard::Key::Numpad2 },
        { SDL_SCANCODE_KP_3, TabGraph::Events::Keyboard::Key::Numpad3 },
        { SDL_SCANCODE_KP_4, TabGraph::Events::Keyboard::Key::Numpad4 },
        { SDL_SCANCODE_KP_5, TabGraph::Events::Keyboard::Key::Numpad5 },
        { SDL_SCANCODE_KP_6, TabGraph::Events::Keyboard::Key::Numpad6 },
        { SDL_SCANCODE_KP_7, TabGraph::Events::Keyboard::Key::Numpad7 },
        { SDL_SCANCODE_KP_8, TabGraph::Events::Keyboard::Key::Numpad8 },
        { SDL_SCANCODE_KP_9, TabGraph::Events::Keyboard::Key::Numpad9 },
        { SDL_SCANCODE_KP_0, TabGraph::Events::Keyboard::Key::Numpad0 },
        { SDL_SCANCODE_KP_PERIOD, TabGraph::Events::Keyboard::Key::NumpadPeriod },
        { SDL_SCANCODE_NONUSBACKSLASH, TabGraph::Events::Keyboard::Key::Nonusbackslash },
        { SDL_SCANCODE_APPLICATION, TabGraph::Events::Keyboard::Key::Application },
        { SDL_SCANCODE_POWER, TabGraph::Events::Keyboard::Key::Power },
        { SDL_SCANCODE_KP_EQUALS, TabGraph::Events::Keyboard::Key::NumpadEquals },
        { SDL_SCANCODE_F13, TabGraph::Events::Keyboard::Key::F13 },
        { SDL_SCANCODE_F14, TabGraph::Events::Keyboard::Key::F14 },
        { SDL_SCANCODE_F15, TabGraph::Events::Keyboard::Key::F15 },
        { SDL_SCANCODE_F16, TabGraph::Events::Keyboard::Key::F16 },
        { SDL_SCANCODE_F17, TabGraph::Events::Keyboard::Key::F17 },
        { SDL_SCANCODE_F18, TabGraph::Events::Keyboard::Key::F18 },
        { SDL_SCANCODE_F19, TabGraph::Events::Keyboard::Key::F19 },
        { SDL_SCANCODE_F20, TabGraph::Events::Keyboard::Key::F20 },
        { SDL_SCANCODE_F21, TabGraph::Events::Keyboard::Key::F21 },
        { SDL_SCANCODE_F22, TabGraph::Events::Keyboard::Key::F22 },
        { SDL_SCANCODE_F23, TabGraph::Events::Keyboard::Key::F23 },
        { SDL_SCANCODE_F24, TabGraph::Events::Keyboard::Key::F24 },
        { SDL_SCANCODE_EXECUTE, TabGraph::Events::Keyboard::Key::Execute },
        { SDL_SCANCODE_HELP, TabGraph::Events::Keyboard::Key::Help },
        { SDL_SCANCODE_MENU, TabGraph::Events::Keyboard::Key::Menu },
        { SDL_SCANCODE_SELECT, TabGraph::Events::Keyboard::Key::Select },
        { SDL_SCANCODE_STOP, TabGraph::Events::Keyboard::Key::Stop },
        { SDL_SCANCODE_AGAIN, TabGraph::Events::Keyboard::Key::Again },
        { SDL_SCANCODE_UNDO, TabGraph::Events::Keyboard::Key::Undo },
        { SDL_SCANCODE_CUT, TabGraph::Events::Keyboard::Key::Cut },
        { SDL_SCANCODE_COPY, TabGraph::Events::Keyboard::Key::Copy },
        { SDL_SCANCODE_PASTE, TabGraph::Events::Keyboard::Key::Paste },
        { SDL_SCANCODE_FIND, TabGraph::Events::Keyboard::Key::Find },
        { SDL_SCANCODE_MUTE, TabGraph::Events::Keyboard::Key::Mute },
        { SDL_SCANCODE_VOLUMEUP, TabGraph::Events::Keyboard::Key::VolumeUp },
        { SDL_SCANCODE_VOLUMEDOWN, TabGraph::Events::Keyboard::Key::VolumeDown },
        //{LockingcapsLock, ,  TabGraph::Events::Keyboard::KeySDL_SCANCODE_LOCKINGCAPSLOCK},
        //{LockingnumLock, ,  TabGraph::Events::Keyboard::KeySDL_SCANCODE_LOCKINGNUMLOCK},
        //{LockingscrollLock, ,  TabGraph::Events::Keyboard::KeySDL_SCANCODE_LOCKINGSCROLLLOCK},
        { SDL_SCANCODE_KP_COMMA, TabGraph::Events::Keyboard::Key::NumpadComma },
        { SDL_SCANCODE_KP_EQUALSAS400, TabGraph::Events::Keyboard::Key::NumpadEqualsas400 },
        { SDL_SCANCODE_INTERNATIONAL1, TabGraph::Events::Keyboard::Key::International1 },
        { SDL_SCANCODE_INTERNATIONAL2, TabGraph::Events::Keyboard::Key::International2 },
        { SDL_SCANCODE_INTERNATIONAL3, TabGraph::Events::Keyboard::Key::International3 },
        { SDL_SCANCODE_INTERNATIONAL4, TabGraph::Events::Keyboard::Key::International4 },
        { SDL_SCANCODE_INTERNATIONAL5, TabGraph::Events::Keyboard::Key::International5 },
        { SDL_SCANCODE_INTERNATIONAL6, TabGraph::Events::Keyboard::Key::International6 },
        { SDL_SCANCODE_INTERNATIONAL7, TabGraph::Events::Keyboard::Key::International7 },
        { SDL_SCANCODE_INTERNATIONAL8, TabGraph::Events::Keyboard::Key::International8 },
        { SDL_SCANCODE_INTERNATIONAL9, TabGraph::Events::Keyboard::Key::International9 },
        { SDL_SCANCODE_LANG1, TabGraph::Events::Keyboard::Key::Lang1 },
        { SDL_SCANCODE_LANG2, TabGraph::Events::Keyboard::Key::Lang2 },
        { SDL_SCANCODE_LANG3, TabGraph::Events::Keyboard::Key::Lang3 },
        { SDL_SCANCODE_LANG4, TabGraph::Events::Keyboard::Key::Lang4 },
        { SDL_SCANCODE_LANG5, TabGraph::Events::Keyboard::Key::Lang5 },
        { SDL_SCANCODE_LANG6, TabGraph::Events::Keyboard::Key::Lang6 },
        { SDL_SCANCODE_LANG7, TabGraph::Events::Keyboard::Key::Lang7 },
        { SDL_SCANCODE_LANG8, TabGraph::Events::Keyboard::Key::Lang8 },
        { SDL_SCANCODE_LANG9, TabGraph::Events::Keyboard::Key::Lang9 },
        { SDL_SCANCODE_ALTERASE, TabGraph::Events::Keyboard::Key::AltErase },
        { SDL_SCANCODE_SYSREQ, TabGraph::Events::Keyboard::Key::SysReq },
        { SDL_SCANCODE_CANCEL, TabGraph::Events::Keyboard::Key::Cancel },
        { SDL_SCANCODE_CLEAR, TabGraph::Events::Keyboard::Key::Clear },
        { SDL_SCANCODE_PRIOR, TabGraph::Events::Keyboard::Key::Prior },
        { SDL_SCANCODE_RETURN2, TabGraph::Events::Keyboard::Key::Return2 },
        { SDL_SCANCODE_SEPARATOR, TabGraph::Events::Keyboard::Key::Separator },
        { SDL_SCANCODE_OUT, TabGraph::Events::Keyboard::Key::Out },
        { SDL_SCANCODE_OPER, TabGraph::Events::Keyboard::Key::Oper },
        { SDL_SCANCODE_CLEARAGAIN, TabGraph::Events::Keyboard::Key::ClearAgain },
        { SDL_SCANCODE_CRSEL, TabGraph::Events::Keyboard::Key::CrSel },
        { SDL_SCANCODE_EXSEL, TabGraph::Events::Keyboard::Key::ExSel },
        { SDL_SCANCODE_KP_00, TabGraph::Events::Keyboard::Key::Numpad00 },
        { SDL_SCANCODE_KP_000, TabGraph::Events::Keyboard::Key::Numpad000 },
        { SDL_SCANCODE_THOUSANDSSEPARATOR, TabGraph::Events::Keyboard::Key::ThousandsSeparator },
        { SDL_SCANCODE_DECIMALSEPARATOR, TabGraph::Events::Keyboard::Key::DecimalSeparator },
        { SDL_SCANCODE_CURRENCYUNIT, TabGraph::Events::Keyboard::Key::CurrencyUnit },
        { SDL_SCANCODE_CURRENCYSUBUNIT, TabGraph::Events::Keyboard::Key::CurrencySubunit },
        { SDL_SCANCODE_KP_LEFTPAREN, TabGraph::Events::Keyboard::Key::NumpadLeftParenthesis },
        { SDL_SCANCODE_KP_RIGHTPAREN, TabGraph::Events::Keyboard::Key::NumpadRightParenthesis },
        { SDL_SCANCODE_KP_LEFTBRACE, TabGraph::Events::Keyboard::Key::NumpadLeftBrace },
        { SDL_SCANCODE_KP_RIGHTBRACE, TabGraph::Events::Keyboard::Key::NumpadRightBrace },
        { SDL_SCANCODE_KP_TAB, TabGraph::Events::Keyboard::Key::NumpadTab },
        { SDL_SCANCODE_KP_BACKSPACE, TabGraph::Events::Keyboard::Key::NumpadBackspace },
        { SDL_SCANCODE_KP_A, TabGraph::Events::Keyboard::Key::NumpadA },
        { SDL_SCANCODE_KP_B, TabGraph::Events::Keyboard::Key::NumpadB },
        { SDL_SCANCODE_KP_C, TabGraph::Events::Keyboard::Key::NumpadC },
        { SDL_SCANCODE_KP_D, TabGraph::Events::Keyboard::Key::NumpadD },
        { SDL_SCANCODE_KP_E, TabGraph::Events::Keyboard::Key::NumpadE },
        { SDL_SCANCODE_KP_F, TabGraph::Events::Keyboard::Key::NumpadF },
        { SDL_SCANCODE_KP_XOR, TabGraph::Events::Keyboard::Key::NumpadXor },
        { SDL_SCANCODE_KP_POWER, TabGraph::Events::Keyboard::Key::NumpadPower },
        { SDL_SCANCODE_KP_PERCENT, TabGraph::Events::Keyboard::Key::NumpadPercent },
        { SDL_SCANCODE_KP_LESS, TabGraph::Events::Keyboard::Key::NumpadLess },
        { SDL_SCANCODE_KP_GREATER, TabGraph::Events::Keyboard::Key::NumpadGreater },
        { SDL_SCANCODE_KP_AMPERSAND, TabGraph::Events::Keyboard::Key::NumpadAmpersand },
        { SDL_SCANCODE_KP_DBLAMPERSAND, TabGraph::Events::Keyboard::Key::NumpadDblAmpersand },
        { SDL_SCANCODE_KP_VERTICALBAR, TabGraph::Events::Keyboard::Key::NumpadVerticalBar },
        { SDL_SCANCODE_KP_DBLVERTICALBAR, TabGraph::Events::Keyboard::Key::NumpadDblVerticalBar },
        { SDL_SCANCODE_KP_COLON, TabGraph::Events::Keyboard::Key::NumpadColon },
        { SDL_SCANCODE_KP_HASH, TabGraph::Events::Keyboard::Key::NumpadHash },
        { SDL_SCANCODE_KP_SPACE, TabGraph::Events::Keyboard::Key::NumpadSpace },
        { SDL_SCANCODE_KP_AT, TabGraph::Events::Keyboard::Key::NumpadAt },
        { SDL_SCANCODE_KP_EXCLAM, TabGraph::Events::Keyboard::Key::NumpadExclam },
        { SDL_SCANCODE_KP_MEMSTORE, TabGraph::Events::Keyboard::Key::NumpadMemStore },
        { SDL_SCANCODE_KP_MEMRECALL, TabGraph::Events::Keyboard::Key::NumpadMemRecall },
        { SDL_SCANCODE_KP_MEMCLEAR, TabGraph::Events::Keyboard::Key::NumpadMemClear },
        { SDL_SCANCODE_KP_MEMADD, TabGraph::Events::Keyboard::Key::NumpadMemAdd },
        { SDL_SCANCODE_KP_MEMSUBTRACT, TabGraph::Events::Keyboard::Key::NumpadMemSubtract },
        { SDL_SCANCODE_KP_MEMMULTIPLY, TabGraph::Events::Keyboard::Key::NumpadMemMultiply },
        { SDL_SCANCODE_KP_MEMDIVIDE, TabGraph::Events::Keyboard::Key::NumpadMemDivide },
        { SDL_SCANCODE_KP_PLUSMINUS, TabGraph::Events::Keyboard::Key::NumpadPlusMinus },
        { SDL_SCANCODE_KP_CLEAR, TabGraph::Events::Keyboard::Key::NumpadClear },
        { SDL_SCANCODE_KP_CLEARENTRY, TabGraph::Events::Keyboard::Key::NumpadClearEntry },
        { SDL_SCANCODE_KP_BINARY, TabGraph::Events::Keyboard::Key::NumpadBinary },
        { SDL_SCANCODE_KP_OCTAL, TabGraph::Events::Keyboard::Key::NumpadOctal },
        { SDL_SCANCODE_KP_DECIMAL, TabGraph::Events::Keyboard::Key::NumpadDecimal },
        { SDL_SCANCODE_KP_HEXADECIMAL, TabGraph::Events::Keyboard::Key::NumpadHexadecimal },
        { SDL_SCANCODE_LCTRL, TabGraph::Events::Keyboard::Key::LCtrl },
        { SDL_SCANCODE_LSHIFT, TabGraph::Events::Keyboard::Key::LShift },
        { SDL_SCANCODE_LALT, TabGraph::Events::Keyboard::Key::LAlt },
        { SDL_SCANCODE_LGUI, TabGraph::Events::Keyboard::Key::LGui },
        { SDL_SCANCODE_RCTRL, TabGraph::Events::Keyboard::Key::RCtrl },
        { SDL_SCANCODE_RSHIFT, TabGraph::Events::Keyboard::Key::RShift },
        { SDL_SCANCODE_RALT, TabGraph::Events::Keyboard::Key::RAlt },
        { SDL_SCANCODE_RGUI, TabGraph::Events::Keyboard::Key::RGui },
        { SDL_SCANCODE_MODE, TabGraph::Events::Keyboard::Key::Mode },
        { SDL_SCANCODE_AUDIONEXT, TabGraph::Events::Keyboard::Key::AudioNext },
        { SDL_SCANCODE_AUDIOPREV, TabGraph::Events::Keyboard::Key::AudioPrev },
        { SDL_SCANCODE_AUDIOSTOP, TabGraph::Events::Keyboard::Key::AudioStop },
        { SDL_SCANCODE_AUDIOPLAY, TabGraph::Events::Keyboard::Key::AudioPlay },
        { SDL_SCANCODE_AUDIOMUTE, TabGraph::Events::Keyboard::Key::AudioMute },
        { SDL_SCANCODE_MEDIASELECT, TabGraph::Events::Keyboard::Key::MediaSelect },
        { SDL_SCANCODE_WWW, TabGraph::Events::Keyboard::Key::WWW },
        { SDL_SCANCODE_MAIL, TabGraph::Events::Keyboard::Key::Mail },
        { SDL_SCANCODE_CALCULATOR, TabGraph::Events::Keyboard::Key::Calculator },
        { SDL_SCANCODE_COMPUTER, TabGraph::Events::Keyboard::Key::Computer },
        { SDL_SCANCODE_AC_SEARCH, TabGraph::Events::Keyboard::Key::AcSearch },
        { SDL_SCANCODE_AC_HOME, TabGraph::Events::Keyboard::Key::AcHome },
        { SDL_SCANCODE_AC_BACK, TabGraph::Events::Keyboard::Key::AcBack },
        { SDL_SCANCODE_AC_FORWARD, TabGraph::Events::Keyboard::Key::AcForward },
        { SDL_SCANCODE_AC_STOP, TabGraph::Events::Keyboard::Key::AcStop },
        { SDL_SCANCODE_AC_REFRESH, TabGraph::Events::Keyboard::Key::AcRefresh },
        { SDL_SCANCODE_AC_BOOKMARKS, TabGraph::Events::Keyboard::Key::AcBookmarks },
        { SDL_SCANCODE_BRIGHTNESSDOWN, TabGraph::Events::Keyboard::Key::BrightnessDown },
        { SDL_SCANCODE_BRIGHTNESSUP, TabGraph::Events::Keyboard::Key::BrightnessUp },
        { SDL_SCANCODE_DISPLAYSWITCH, TabGraph::Events::Keyboard::Key::DisplaySwitch },
        { SDL_SCANCODE_KBDILLUMTOGGLE, TabGraph::Events::Keyboard::Key::KbdillumToggle },
        { SDL_SCANCODE_KBDILLUMDOWN, TabGraph::Events::Keyboard::Key::KbdillumDown },
        { SDL_SCANCODE_KBDILLUMUP, TabGraph::Events::Keyboard::Key::KbdillumUp },
        { SDL_SCANCODE_EJECT, TabGraph::Events::Keyboard::Key::Eject },
        { SDL_SCANCODE_SLEEP, TabGraph::Events::Keyboard::Key::Sleep },
        { SDL_SCANCODE_APP1, TabGraph::Events::Keyboard::Key::App1 },
        { SDL_SCANCODE_APP2, TabGraph::Events::Keyboard::Key::App2 },
        { SDL_SCANCODE_AUDIOREWIND, TabGraph::Events::Keyboard::Key::AudioRewind },
        { SDL_SCANCODE_AUDIOFASTFORWARD, TabGraph::Events::Keyboard::Key::AudioFastforward },
        { SDL_NUM_SCANCODES, TabGraph::Events::Keyboard::Key::MaxValue }
    };
    const static auto s_reverseKeyLUT { [&]() {
        std::unordered_map<TabGraph::Events::Keyboard::Key, SDL_Scancode> map;
        for (const auto& [key, value] : s_keyLUT)
            map[value] = key;
        return map;
    }() };
    auto GetKey(SDL_Scancode scanCode)
    {
        return s_keyLUT.at(scanCode);
    };
    Events::Event::Keyboard CreateEventData(const SDL_KeyboardEvent& event)
    {
        return {
            Core::Window::Get(event.windowID),
            Keyboard::GetKey(event.keysym.scancode),
            event.state == SDL_PRESSED,
            event.repeat != 0,
            (event.keysym.mod | KMOD_ALT) != 0,
            (event.keysym.mod | KMOD_CTRL) != 0,
            (event.keysym.mod | KMOD_SHIFT) != 0
        };
    }
    Events::Event::TextEdit CreateEventData(const SDL_TextEditingEvent& event)
    {
        return {
            Core::Window::Get(event.windowID),
            event.text,
            size_t(event.start),
            size_t(event.length)
        };
    }
    Events::Event::TextInput CreateEventData(const SDL_TextInputEvent& event)
    {
        return {
            Core::Window::Get(event.windowID),
            event.text
        };
    }
}

namespace TabGraph::Events::Keyboard {
bool InputDevice::GetKeyState(Keyboard::Key key)
{
    return SDL_GetKeyboardState(nullptr)[size_t(TabGraph::SDL2::Keyboard::s_reverseKeyLUT.at(key))];
}

InputDevice::InputDevice()
{
    Events::Manager::On(Event::Type::KeyUp).ConnectMember(this, &InputDevice::_ProcessEvent);
    Events::Manager::On(Event::Type::KeyDown).ConnectMember(this, &InputDevice::_ProcessEvent);
}
};
