/*
* @Author: gpinchon
* @Date:   2019-02-22 16:19:03
* @Last Modified by:   gpinchon
* @Last Modified time: 2021-05-20 12:11:35
*/

#pragma once

#include <Event/Event.hpp>
#include <Event/Signal.hpp>

class InputDevice;

/** Handles InputDevice and events generated by the Engine
*/
class EventsManager : public Trackable {
public:
    class Impl;
    static void Add(InputDevice *device, Event::Type event_type);
    static void Remove(InputDevice *device, Event::Type event_type);
    static void PollEvents();

private:
    EventsManager();
    static EventsManager& _Get();
    std::unique_ptr<Impl> _impl;
};
