/*
* @Author: gpinchon
* @Date:   2019-02-22 16:19:03
* @Last Modified by:   gpinchon
* @Last Modified time: 2021-05-20 12:11:35
*/

#pragma once

#include <Event/Event.hpp>
#include <Event/Signal.hpp>

/** Handles InputDevice and events generated by the Engine
*/
struct EventsManager : Trackable {
    class Impl;
    static Signal<const Event&> &On(Event::Type);
    static void PushEvent(const Event& event);
    static void PollEvents();

private:
    EventsManager();
    static EventsManager& _Get();
    std::unique_ptr<Impl> _impl;
};
