/*
* @Author: gpinchon
* @Date:   2019-02-22 16:19:03
* @Last Modified by:   gpinchon
* @Last Modified time: 2021-07-01 22:14:34
*/

#pragma once

////////////////////////////////////////////////////////////////////////////////
// Includes
////////////////////////////////////////////////////////////////////////////////
#include <Events/Event.hpp>
#include <Events/Signal.hpp>

////////////////////////////////////////////////////////////////////////////////
// Class Definition
////////////////////////////////////////////////////////////////////////////////
namespace TabGraph::Events {
/** @brief Handles InputDevice and events generated by the Engine */
struct Manager : Trackable {
    class Impl;
    static Signal<const Event&>& On(Event::Type);
    static void PushEvent(const Event& event);
    static void PollEvents();

private:
    Manager();
    static Manager& _Get();
    std::unique_ptr<Impl> _impl;
};
}
